/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { VideoboxItem } from "./types";
export namespace Components {
    interface VideoboxStripContainer {
    }
    interface VideoboxStripItem {
        "index": number;
        "item": VideoboxItem;
    }
    interface VideoboxVideo {
        "active": boolean;
        "src": string;
    }
}
declare global {
    interface HTMLVideoboxStripContainerElement extends Components.VideoboxStripContainer, HTMLStencilElement {
    }
    var HTMLVideoboxStripContainerElement: {
        prototype: HTMLVideoboxStripContainerElement;
        new (): HTMLVideoboxStripContainerElement;
    };
    interface HTMLVideoboxStripItemElement extends Components.VideoboxStripItem, HTMLStencilElement {
    }
    var HTMLVideoboxStripItemElement: {
        prototype: HTMLVideoboxStripItemElement;
        new (): HTMLVideoboxStripItemElement;
    };
    interface HTMLVideoboxVideoElement extends Components.VideoboxVideo, HTMLStencilElement {
    }
    var HTMLVideoboxVideoElement: {
        prototype: HTMLVideoboxVideoElement;
        new (): HTMLVideoboxVideoElement;
    };
    interface HTMLElementTagNameMap {
        "videobox-strip-container": HTMLVideoboxStripContainerElement;
        "videobox-strip-item": HTMLVideoboxStripItemElement;
        "videobox-video": HTMLVideoboxVideoElement;
    }
}
declare namespace LocalJSX {
    interface VideoboxStripContainer {
    }
    interface VideoboxStripItem {
        "index"?: number;
        "item"?: VideoboxItem;
    }
    interface VideoboxVideo {
        "active"?: boolean;
        "src"?: string;
    }
    interface IntrinsicElements {
        "videobox-strip-container": VideoboxStripContainer;
        "videobox-strip-item": VideoboxStripItem;
        "videobox-video": VideoboxVideo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "videobox-strip-container": LocalJSX.VideoboxStripContainer & JSXBase.HTMLAttributes<HTMLVideoboxStripContainerElement>;
            "videobox-strip-item": LocalJSX.VideoboxStripItem & JSXBase.HTMLAttributes<HTMLVideoboxStripItemElement>;
            "videobox-video": LocalJSX.VideoboxVideo & JSXBase.HTMLAttributes<HTMLVideoboxVideoElement>;
        }
    }
}
