/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VideoboxStripContainer {
        "data": { title: string, desc: string}[];
    }
    interface VideoboxStripItem {
        "desc": string;
        "src": string;
        "title": string;
    }
}
declare global {
    interface HTMLVideoboxStripContainerElement extends Components.VideoboxStripContainer, HTMLStencilElement {
    }
    var HTMLVideoboxStripContainerElement: {
        prototype: HTMLVideoboxStripContainerElement;
        new (): HTMLVideoboxStripContainerElement;
    };
    interface HTMLVideoboxStripItemElement extends Components.VideoboxStripItem, HTMLStencilElement {
    }
    var HTMLVideoboxStripItemElement: {
        prototype: HTMLVideoboxStripItemElement;
        new (): HTMLVideoboxStripItemElement;
    };
    interface HTMLElementTagNameMap {
        "videobox-strip-container": HTMLVideoboxStripContainerElement;
        "videobox-strip-item": HTMLVideoboxStripItemElement;
    }
}
declare namespace LocalJSX {
    interface VideoboxStripContainer {
        "data"?: { title: string, desc: string}[];
    }
    interface VideoboxStripItem {
        "desc"?: string;
        "src"?: string;
        "title"?: string;
    }
    interface IntrinsicElements {
        "videobox-strip-container": VideoboxStripContainer;
        "videobox-strip-item": VideoboxStripItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "videobox-strip-container": LocalJSX.VideoboxStripContainer & JSXBase.HTMLAttributes<HTMLVideoboxStripContainerElement>;
            "videobox-strip-item": LocalJSX.VideoboxStripItem & JSXBase.HTMLAttributes<HTMLVideoboxStripItemElement>;
        }
    }
}
